---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap-values
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: manifests/flux-tap/multi-cluster/overlays/iterate/tap-values
  prune: true
  sourceRef:
    kind: GitRepository
    name: tap-installation
    namespace: tanzu-continuousdelivery-resources
  decryption:
      provider: sops
      secretRef:
        name: sops-keys