#@ load("@ytt:overlay", "overlay")

# Override issuer of Prometheus certificate
#@overlay/match by=lambda indexOrKey, left, right: left["metadata"]["name"].startswith("prometheus-tls-cert"), expects=1
---
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    # Replace with the name of a pre-existing Cluster Issuer
    name: tmc-issuer