# Reference https://docs.vmware.com/en/VMware-Tanzu-Packages/2023.9.19/tanzu-packages/packages-harbor.html#config

core:
  replicas: 1
  # Used during communication with other components
  secret: "This value is set in a different yaml file"
  # Must be 32 chars
  xsrfKey: "This value is set in a different yaml file"
database:
  password: "This value is set in a different yaml file"

harborAdminPassword: "This value is set in a different yaml file"
hostname: harbor.h2o-2-19237.h2o.vmware.com

jobservice:
  secret: "This value is set in a different yaml file"

pspNames: vmware-system-restricted
registry:
  replicas: 1
  secret: "This value is set in a different yaml file"
# Used for encryption, must be 16 chars.
secretKey: "This value is set in a different yaml file"
tlsCertificate:
  tlsSecretLabels: 
    "managed-by": "vmware-vRegistry"
