---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: configure-cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: deploy-cert-manager
  interval: 1m0s
  path: manifests/flux-tap/multi-cluster/base/configure-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: tap-installation
    namespace: tanzu-continuousdelivery-resources
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  healthChecks:
    - apiVersion: cert-manager.io/v1
      kind: ClusterIssuer
      name: root-ca
