---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deploy-cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: manifests/flux-tap/multi-cluster/base/deploy-cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: tap-installation
    namespace: tanzu-continuousdelivery-resources
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  healthChecks:
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      name: cert-manager
      namespace: tkg-system
