---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: configure-cert-manager
    - name: tap-values
  interval: 1m0s
  path: manifests/flux-tap/multi-cluster/base/tap
  prune: true
  sourceRef:
    kind: GitRepository
    name: tap-installation
    namespace: tanzu-continuousdelivery-resources
  decryption:
    provider: sops
    secretRef:
      name: sops-keys
  healthChecks:
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      name: tap
      namespace: tap-install