---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: external-plain-manifests-app
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: manifests/flux-apps/plain-manifests/
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster-setup-repo
    namespace: tanzu-continuousdelivery-resources
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: the-deployment
      namespace: the-deployment
