- !policy
  id: automation
  body:
    - !layer
      id: mgmt-layer

    - !host-factory
        id: mgmt-appliances
        annotations:
          description: Factory to create mgmt VMs
        layers: [ !layer mgmt-layer ]