# Service account used for the installation of TAP
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tap-install-sa
  namespace: tap-install
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tap-install-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tap-install-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tap-install-cluster-role
subjects:
- kind: ServiceAccount
  name: tap-install-sa
  namespace: tap-install