apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- contour-package-install.yaml

secretGenerator:
- name: contour-tkg-system-values
  namespace: tkg-system
  files:
  - contour-values.yaml
  type: Opaque
  options:
    annotations:
      tkg.tanzu.vmware.com/tanzu-package: contour-tkg-system