# This manifest can be used instead of the ingress object create by the Helm chart. Only the webservice
# is exposed.
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gitlab
  namespace: gitlab
spec:
  routes:
    - services:
        - name: gitlab-webservice-default
          port: 8181
  virtualhost:
    fqdn: gitlab.h2o-2-21094.h2o.vmware.com
    tls:
      secretName: gitlab-wildcard-tls