---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tanzu-packages-cert-manager
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: manifests/flux/tanzu-packages/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
    namespace: tanzu-continuousdelivery-resources
