formatter: "markdown table"

recursive:
  enabled: true

sections:
  show:
    - inputs
    - outputs

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    <!-- This section will be overridden by terraform-docs. Do not change it.-->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false

sort:
  enabled: true
  by: required

settings:
  anchor: false
  color: true
  default: true
  description: false
  escape: true
  hide-empty: true
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true