# permissions for end users to view podtrackers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podtracker-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: pod-tracker
    app.kubernetes.io/part-of: pod-tracker
    app.kubernetes.io/managed-by: kustomize
  name: podtracker-viewer-role
rules:
  - apiGroups:
      - pods.giovannibaratta.local
    resources:
      - podtrackers
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - pods.giovannibaratta.local
    resources:
      - podtrackers/status
    verbs:
      - get
