# Deploy a Self signed CA. The first issuer is used to generate the certificate
# and private key of the CA, the second issuer is the proper CA.
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-bootstrapper
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-ca-cert
  namespace: cert-manager
spec:
  isCA: true
  commonName: Self Signed CA
  secretName: self-signed-root-ca-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: ca-bootstrapper
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: tmc-issuer
spec:
  ca:
    secretName: self-signed-root-ca-tls