apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageRepository
metadata:
  name: tap-pkgr
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgr
spec:
  fetch:
    imgpkgBundle:
      image: harbor.h2o-2-22574.h2o.vmware.com/tap/tap-packages:1.7.4