apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-kustomization

commonLabels:
  managed-by: kustomize

resources:
- namespace.yaml
- deployment.yaml
- tanzu-packages/cert-manager.yaml
- tanzu-packages/contour.yaml

# Adjust the dependencies to include the name with the namePrefix
# replacements:
# - source:
#     group: kustomize.toolkit.fluxcd.io/v1beta2
#     kind: Kustomization
#     name: tanzu-packages-cert-manager
#     fieldPath: metadata.name
#   targets:
#   - select:
#       group: kustomize.toolkit.fluxcd.io/v1beta2
#       kind: Kustomization
#       name: tanzu-packages-contour
#     fieldPath: spec.dependsOn.0.name