apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-kustomization

commonLabels:
  managed-by: kustomize

resources:
  - namespace.yaml
  - deployment.yaml
  - tanzu-packages/cert-manager.yaml
  - tanzu-packages/contour.yaml
