apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helm-based-app
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  chart:
    spec:
      chart: manifests/flux-apps/helm-based/

      version: '0.0.1'
      sourceRef:
        kind: GitRepository
        name: cluster-setup-repo
        namespace: tanzu-continuousdelivery-resources
      interval: 1m
  releaseName: helm-based-app
  targetNamespace: helm-based-app
  values: