apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: configure-cert-manager

resources:
  - cert-manager.yaml

secretGenerator:
  - name: self-signed-root-ca-tls
    namespace: cert-manager
    files:
      - tls.key=root-ca.key.encrypted
      - tls.crt=root-ca.crt
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
