# Expose app on port 8080

apiVersion: apps/v1
kind: Deployment
metadata:
  name: required-for-kustomize-but-not-used
spec:
  template:
    spec:
      containers:
      - name: vote
        command:
        - "gunicorn"
        args:
        - "app:app"
        - "-b"
        - "0.0.0.0:8080"
        - "--log-file"
        - "-"
        - "--access-logfile"
        - "-"
        - "--workers"
        - "4"
        - "--keep-alive"
        - "0"
        env:
        - value: "8080"
          name: PORT
        ports:
        - containerPort: 8080
          name: vote
        - $patch: replace