apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:vmware-system-restricted:TO_BE_REPLACED_DURING_APPLY
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  # ClusterRole created during the deployment
  name: psp:vmware-system-restricted
subjects:
- kind: ServiceAccount
  name: TO_BE_REPLACED_DURING_APPLY
  namespace: TO_BE_REPLACED_DURING_APPLY