apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tap-values

secretGenerator:
 - name: tap-values
   namespace: tap-install
   files:
   - values.yaml=tap-values.yaml.encrypted
   options:
    disableNameSuffixHash: true