apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: plain-manifests-app
  namespace: tanzu-continuousdelivery-resources
spec:
  patches:
    - patch: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: the-deployment
          namespace: the-deployment

        spec:
          replicas: 3
      target:
        kind: Deployment
        name: the-deployment
        namespace: the-deployment