conjur_appliance_url: "https://172.17.0.11"
conjur_account: "lab"
conjur_validate_certs: no
conjur_ssl_certificate: |
  -----BEGIN CERTIFICATE-----
  MIIDLjCCAhagAwIBAgIUTFjZ8etHY8xKk7iDap6Klp+YSkwwDQYJKoZIhvcNAQEL
  BQAwLjELMAkGA1UEBhMCSVQxDzANBgNVBAgMBk1vZGVuYTEOMAwGA1UEAwwFcHJv
  eHkwHhcNMjMxMTA2MTUyMTAyWhcNMjQxMTA1MTUyMTAyWjAuMQswCQYDVQQGEwJJ
  VDEPMA0GA1UECAwGTW9kZW5hMQ4wDAYDVQQDDAVwcm94eTCCASIwDQYJKoZIhvcN
  AQEBBQADggEPADCCAQoCggEBAK14m8x0Dp4GX4A5z1J/kjwYVwE+gDxHNi1US6pt
  +u5A6W5g0dMrjXohe43zFRwbxROFvXbUKdVGhvd0d5dG1Tn5yxAKUfKvkwUApR9R
  41XwfZSpBVxVIKrqLRb5vJXPtFdj/GSwI+fRloYpnN4kvlCjN44s3K0qeaJtNEyJ
  htFEgQsvyIBZDt2cRoUjLE71zPqoRllsfU6+8EzJbCm8nOKb9jK8vt+kuDasWKfD
  gVbTB7qEm73J380ZChBFXe3EO53TcqziraCu2yNzZTrouD9F/zfnObVT75kHOE6Y
  OgefjoI9qieMhCDJlyZ0aGLA1eksYDoN0gi+RKahd86YlL0CAwEAAaNEMEIwIQYD
  VR0RBBowGIIJbG9jYWxob3N0ggVwcm94eYcErBEACzAdBgNVHQ4EFgQUNVlOm003
  ADkeMfEiOrK1NJPqZCwwDQYJKoZIhvcNAQELBQADggEBAJaAox2UaIUmtbH6JBS2
  peAMVzSDkQGG/zLOHV5QXe7vFqRdd9w8dcxmdI4M6bSK8/BBZAJgc/O6V3Ss8xRl
  Pqlg7ezDl+04Bsz168TsyxnCKq3dC3fpfZOpFbcTnqMI+wV99fJn2nl3BW+q3mlD
  ZpnoOeZJBgIv/U9n3nkMXV+KWJNLFw9wFwUzpWTR3d1xkG2FoJLNVKcykjnTiVis
  8MB2VZaqpU80IltKG/TYVcyibREV1TERZPZ5S9ZlQGFTUJWYEp+g+sBPLqQFTrj6
  3lE2+d1nRuRtDDuFLs2C9BS41Daore56IM+KLYfpKrQNvdhVhxPZUG8Y/biPo2Nt
  Q2U=
  -----END CERTIFICATE-----
