# artifacts_dir variable must be defined by the user
keycloak_tls_cert: "{{ lookup('ansible.builtin.file', artifacts_dir + '/tls/certificate.pem') }}"
keycloak_tls_ca_chain: "{{ lookup('ansible.builtin.file', artifacts_dir + '/tls/issuer.pem') }}"
keycloak_tls_private_key: "{{ lookup('ansible.builtin.file', artifacts_dir + '/tls/private-key.pem') }}"