namespaceOverride: jenkins
clusterZone: "local.lan"

controller:
  tag: 2.432-jdk17

  installPlugins:
    - kubernetes:4132.v758a_0c613a_38
    - git:5.2.1
    - configuration-as-code:1737.v652ee9b_a_e0d9
    - oic-auth:2.6

  serviceType: ClusterIP
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/force-ssl-redirect: "true"
      kubernetes.io/ingress.allow-http: "false"
      # Delegate certificate generations to cert-manager
      cert-manager.io/issuer: selfsigned-issuer
    hostName: jenkins.local.lan
    tls:
    # The secret is generate by cert-manager
    - secretName: jenkins-tls
      hosts:
      - jenkins.local.lan

  JCasC:
    defaultConfig: false

    configScripts:
      jenkins-config: |
        unclassified:
          location:
            url: "https://jenkins.local.lan"
      security-realm-config: |
        jenkins:
          securityRealm:
            oic:
              authorizationServerUrl: "https://keycloak.local.lan/realms/tanzu"
              clientId: "jenkins-oidc-auth"
              clientSecret: "${OIDC_CLIENT_SECRET}"
              disableSslVerification: true
              tokenAuthMethod: "client_secret_post"
              tokenServerUrl: "https://keycloak.local.lan/auth/realms/tanzu/protocol/openid-connect/token"
              userNameField: "preferred_username"
              scopes: "email groups profile openid"
              groupsFieldName: "groups"
              emailFieldName: "email"
              wellKnownOpenIDConfigurationUrl: "https://keycloak.local.lan/realms/tanzu/.well-known/openid-configuration"

    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false