# Reference https://docs.vmware.com/en/VMware-Tanzu-Packages/2023.9.19/tanzu-packages/packages-harbor.html#config

core:
  secret: "REPLACE_ME"
  xsrfKey: "REPLACE_ME"
database:
  password: "REPLACE_ME"

harborAdminPassword: "REPLACE_ME"

jobservice:
  secret: "REPLACE_ME"

registry:
  secret: "REPLACE_ME"

secretKey: "REPLACE_ME"