---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 1m0s
  path: manifests/flux-tap/tap/
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-branch-tap-gitops-flux
    namespace: tanzu-continuousdelivery-resources
  decryption:
      provider: sops
      secretRef:
        name: sops-keys