- !policy
  id: automation
  body:
    - !layer mgmt-layer

    - !host
      id: ansible
      annotations:
        description: Ansible controller

    # The host factory is used by Ansible to
    # generate new hosts dynamically
    - !host-factory
      id: mgmt-appliances
      annotations:
        description: Factory to create mgmt VMs
      layers: [ !layer mgmt-layer ]

    # This is just a group of resources. The name secrets is arbitrary.
    - &secrets
      - !variable
        id: keycloak/db_pass
        kind: password
        annotations:
          description: Database password used by Keycloak

      - !variable
        id: keycloak/admin_pass
        kind: password
        annotations:
          description: Admin password to access Keycloak

      - !variable
        id: minio/root_password
        kind: password
        annotations:
          description: Root password to access MinIO

      - !variable
        id: minio/backup_secretkey
        kind: password
        annotations:
          description: Secret key to use for access by the backup user

    - !group secrets-reader

    - !grant
      role: !group secrets-reader
      members:
        - !host ansible

    - !permit
      role: !group secrets-reader
      privileges: [read, execute]
      resource: *secrets