apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tap

resources:
  - service-account.yaml
  - package-repository.yaml
  - package-install.yaml
  - registry-credentials-exporter.yaml

secretGenerator:
  - name: registry-credentials
    namespace: tap-install
    files:
      - .dockerconfigjson=registry-credentials-docker-config.json.encrypted
    type: kubernetes.io/dockerconfigjson
    options:
      disableNameSuffixHash: true
