apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tap

resources:
  - service-account.yaml
  - package-repository.yaml
  - package-install.yaml
  - cert-manager.yaml
  - registry-credentials-exporter.yaml

secretGenerator:
  - name: self-signed-root-ca-tls
    namespace: cert-manager
    files:
      - tls.key=root-ca.key.encrypted
      - tls.crt=root-ca.crt
    type: kubernetes.io/tls
    options:
      disableNameSuffixHash: true
  - name: registry-credentials
    namespace: tap-install
    files:
      - .dockerconfigjson=registry-credentials-docker-config.json.encrypted
    type: kubernetes.io/dockerconfigjson
    options:
      disableNameSuffixHash: true
