# This file contains a list of shared resources that must be applied to all the clusters
# that are part of the "external" group. All the overlays should reference this file like shown below.

# Block to include in the overlays
# components:
#  - <path to the folder containing this file>

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - ../../../../apps/external-plain-manifests
  - ../../../../apps/helm-based
  - ../../../../apps/monorepo-manifests

patches:
  - path: patches/external-plain-manifests-app.yaml
  - path: patches/helm-based-app.yaml
  - path: patches/monorepo-manifests-app.yaml
